### ISSUE TITLE
filemanager.sol issues

### ISSUE THREAD

**Issue by dmitro3** [shepherliu/multichain-cloud#1]
Hi,
I think there is a error in filemanager.sol .when I try to test this function getIndexsByFileType it will return (-32000) out of gas.but with contract you already deployed it work norman

**Comment by shepherliu** [comment]
> Hi, I think there is a error in filemanager.sol .when I try to test this function getIndexsByFileType it will return (-32000) out of gas.but with contract you already deployed it work norman

Hi, thank you, this issue has been fixed now.
